# Generated by Django 5.1.2 on 2024-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_project_owner_alter_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
